apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-config
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://github.com/Hejle/traefik-argocd.git
    targetRevision: master
    path: traefik-overrides
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-log-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hejle/traefik-argocd.git
    targetRevision: master
    path: traefik-dashboard
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
