apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-logs
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-traefik-logs