apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-logs
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-static
  volumeName: pv-traefik-logs